kallisto:
  filt_adata: /nanopore/pipeline_output_kallisto/{plate}/{subpool}/filtered_adata.h5ad
  unfilt_adata: /nanopore/pipeline_output_kallisto/{plate}/{subpool}/unfiltered_adata.h5ad

klue:
  unfilt_adata: /nanopore/pipeline_output_klue/{plate}/{subpool}/{mult_genotype_1}_{mult_genotype_2}/unfiltered_adata.h5ad

  # version with all genotypes
  genotype_counts: /nanopore/pipeline_output_klue/{plate}/{subpool}/genotype_counts.tsv

scrublet:
  adata: /nanopore/scrublet/{plate}/{sample}/{subpool}/adata.h5ad
  scrub_adata: /nanopore/scrublet/{plate}/{sample}/{subpool}/scrubbed_adata.h5ad
  
cellbender:
  filt_h5: /nanopore/cellbender/{plate}/{subpool}/adata_denoised_filtered.h5
  filt_adata: /nanopore/pipeline_output_cellbender/{plate}/{subpool}/filtered_adata_denoised.h5ad
  ckpt_tar: /nanopore/cellbender/{plate}/{subpool}/ckpt.tar.gz
  genotype_adata: /nanopore/pipeline_output_cellbender/{plate}/{subpool}/filtered_adata_denoised_with_klue.h5ad
  
tissue:
  adata: /nanopore/{plate}/{tissue}/adata.h5ad
